import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 网站介绍',
    },
    {
      type: 'category',
      label: '📚 付费知识',
      items: [
        {
          type: 'autogenerated',
          dirName: '付费知识',
        },
      ],
    },
    {
      type: 'category',
      label: '🛠️ 技术指南',
      items: [
        {
          type: 'autogenerated',
          dirName: '技术指南',
        },
      ],
    },
    {
      type: 'category',
      label: '📅 每日更新',
      items: [
        {
          type: 'autogenerated',
          dirName: '每日更新',
        },
      ],
    },
  ],
};

export default sidebars;