import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 网站介绍',
    },
    {
      type: 'category',
      label: '01 · 深度知识',
      items: [
        {
          type: 'autogenerated',
          dirName: 'paid-knowledge',
        },
        '付费知识/示例文章',
      ],
    },
    {
      type: 'category',
      label: '02 · 工程实践',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dev-guides',
        },
        '技术指南/入门教程',
      ],
    },
    {
      type: 'category',
      label: '03 · 科技前沿',
      items: [
        {
          type: 'autogenerated',
          dirName: '每日更新',
        },
      ],
    },
  ],
};

export default sidebars;
